server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_admins
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    
#  main:
#    allow-circular-references: true